### PR TITLE
Modernise python tooling

### PR DESCRIPTION
**Pull request by niksirbi**

### CODE REVIEW

**Comment by niksirbi** [comment]
- Had to increase line length to 127 (as is now), because black cannot auto-format docstrings (have to be done manually)
- Had to turn-off mypy pre-commit hooks (many errors otherwise)
- Had to exclude experimental data from hooks in an awkward way (move elsewhere)

**Comment by adamltyson** [comment]
@niksirbi I think the error is because there are tests that produce graphical outputs that the CI doesn't like. These tests (e.g. [this one](https://github.com/neuroinformatics-unit/NeuralPlayground/blob/13cce2b3b0430b3952df328fca2677836ebf7324/tests/arena_exp_test.py#L49)) don't seem to assert anything, so we could either:
* remove them
* handle graphics properly and check that the figure being produced is correct

**Comment by adamltyson** [comment]
@niksirbi found a simple fix for this for now. I've raised https://github.com/ClementineDomine/NeuralPlayground/issues/49 to track the general issue of testing the visualisation.

**Comment by adamltyson** [comment]
@niksirbi is there anything else to be done on this initial pass? Looks good for a PR upstream to me.

**Comment by niksirbi** [comment]
> @niksirbi is there anything else to be done on this initial pass? Looks good for a PR upstream to me.

Yeap, I'll open an upstream right away, with more explanations of the changes we've made.

**Pull request closed without merging**
